In [1]:
import borehole_tables as bt

In [7]:
clf2 = bt.train(0)

training with all labelled samples
test set size:  0.2
[Pipeline] .......... (step 1 of 3) Processing list2str, total=   0.0s
[Pipeline] ............. (step 2 of 3) Processing tfidf, total=   0.6s
[Pipeline] ............... (step 3 of 3) Processing cnb, total=   0.0s
Test set results: 
0.8966942148760331
[[596  74]
 [  1  55]]
For manually annotated:
0.9181141439205955
[[3079  291]
 [   6  251]]


In [5]:
res = bt.get_bh_tables_from_docid(['2646', '44448', '32730', '37802', '44603'])

Getting borehole tables for  2646
Num of all tables:  3 , num of borehole tables:  2
Borehole tables: 
    Bore  Total Depth  Depth to Coal  Coal Thickness 
0     NaN         ft.            ft.             ft. 
1   -A35          350            185               6 
2    A36          302             NaN             NaN
3    A37          400             NaN             NaN
4    A38          130             NaN             NaN
5   A38A          115             NaN             NaN
6    A39          158             NaN             NaN
7    A40          188            176               9 
8    A41          175             NaN             NaN
9    A42          457            455              10 
10   A43          110             NaN             NaN
11   A44          200             NaN             NaN
        Bore  Seam Thickness  Recovery  Moisture   Ash  Vol. M.   S.I. 
0         NaN             NaN  e F1.45         %     %        %     NaN
1        A35         4" lo1"      94.4       3.6   

Num of all tables:  4 , num of borehole tables:  2
Borehole tables: 
    HOLE     EASTING     NORTHING       RL  DRILLED       DATE   DEPTH   \
0     NaN        (m)          (m)      (m)       BY   yy/mm/dd     (m)    
2  9758.0  645759.23   7592449.38   227.52   Weston     990519    97.0    
3  9759.0  644803.90   7592439.18   234.84   Weston     990520    91.0    
4  9760.0  639640.18   7594409.56   247.02   Weston     990520    91.0    
5  9761.0  640529.79   7595196.48   239.15   Weston     990520   103.0    
6  9762.0  639634.70   7595996.51   251.83   Weston     990520    91.0    
7  9763.0  638017.56   7598020.73   251.81   Weston     990521    91.0    
8  9764.0  641238.98   7594322.46   231.06   Weston     990521   109.0    

  CASED      BIT   SIZE  GEOLOGY       LOGGED  DEPTH .1 SONDES   
0   (m)       NaN  (mm)       BY           BY      (m)     (1)   
2  16.0   Blades    120    G Sau       Reeves     96.9    GDCV   
3   9.0   Blades    120   G Saul   Not logged       NaN  

Num of all tables:  140 , num of borehole tables:  114
Borehole tables: 
  Hole No.   Easting AGD84 Zone 54   Northing AGD84 Zone 54  Azm   Dip   \
0    EHND2                   472450                  7797800   -    -90   
1    EHND3                   458424                  7787214   -    -90   
2    EHND4                   461217                  7781508   -    -90   
3    EHND5                   463150                  7781800   -    -90   
4    EHND6                   465600                  7784200   -    -90   
5    EHND7                   449800                  7782000   -    -90   
6    EHND8                   452000                  7787200   -    -90   
7   EHND9A                   472446                  7797815  NaN   -90   

  Basement depth m   Depth m   
0                -       43.0  
1            272.5      315.3  
2            237.3      302.3  
3            239.3      336.2  
4           212.35      402.7  
5            185.0      261.8  
6            267.2      292

     GRID 1  PROSPECT:                                             Site 5   \
0    COLLAR     COORDS                                  465600E, 7784200N    
1  FROM (m)     TO (m)   LITHOLOGICAL & MINERALOGICAL DESCRIPTION (+ Ge...   
2        NaN        NaN                                                NaN   
3    301.39     304.89   Medium to coarse-grained actinolite-magnetite-...   
5    304.89     306.26   Medium to coarse-grained actinolite-magnetite-...   
7    306.26     307.40   Strongly chlorite-biotite-sericite-magnetite-a...   

                                          R.L. (m):   \
0                                   COLLAR AZIMUTH:    
1                              ALTERATION & VEINING    
2                                                NaN   
3  Magnetite, actinolite, epidote, scapolite, ser...   
5  actinolite-magnetite-epidote- biotite-scapolit...   
7  chlorite-biotite-sericite-magnetite alteration...   

                                    WATER DEPTH (m)   \
0   

10        NaN         NaN         NaN  
   Unnamed: 0      Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 PGM-MS23   \
0         NaN             NaN        NaN        NaN        NaN       Au    
1    Hole No   Sample Number       From         To   Interval       ppm    
2      EHND3      EHND3 -001        278        279          1     0.002    
3      EHND3      EHND3 -002        287        288          1     0.003    
4      EHND3      EHND3 -003        289        290          1     0.002    
5      EHND3      EHND3 -004        290        291          1     0.001    
6      EHND3      EHND3 -005        299        300          1     0.001    
7      EHND3      EHND3 -006        301        302          1     0.002    
8      EHND3      EHND3 -007        309        310          1     0.001    
9      EHND3      EHND3 -008        312        313          1     0.001    
10     EHND3      EHND3 -009        294        295          1     0.001    
11     EHND4       EHND4 001        246        2

33          <1   
   Unnamed: 0      Unnamed: 1 ME-ICP61s  ME-ICP61s .1 ME-ICP61s .2  \
0         NaN             NaN        Ca           Cd           Co    
1    Hole No   Sample Number          %          ppm          ppm    
2      EHND6       EHND6 029       6.86         <0.5           69    
3      EHND6       EHND6 030       6.24         <0.5           50    
4      EHND6       EHND6 031       6.48          0.5          153    
5      EHND6       EHND6 032       6.11         <0.5           88    
6      EHND6       EHND6 033       5.79         <0.5           55    
7      EHND6       EHND6 034       5.87         <0.5           47    
8      EHND6       EHND6 035       5.86         <0.5           41    
9      EHND6       EHND6 036       5.28         <0.5          140    
10     EHND6       EHND6 037       5.86         <0.5           68    
11     EHND6       EHND6 038        5.7         <0.5           43    
12     EHND6       EHND6 039       5.74         <0.5           37    
13

34         <10   
   Unnamed: 0      Unnamed: 1 ME-ICP61S  ME-ICP61s  ME-ICP61s .1 ME-ICP61s .2  \
0         NaN             NaN        Na         Ni            P           Pb    
1    Hole No   Sample Number          %        ppm          ppm          ppm    
2      EHND6       EHND6 062       1.32         13         9720            8    
3      EHND6       EHND6 063       1.12         15         9450           10    
4      EHND6       EHND6 064        1.1         19         8110            8    
5      EHND6       EHND6 065       1.19         21         9100            9    
6      EHND6       EHND6 066       1.18         22        10700            9    
7      EHND6       EHND6 067       1.73         14         9800            4    
8      EHND6       EHND6 068       1.97         17         7780           13    
9      EHND6       EHND6 069       0.45         59         7000           12    
10     EHND6       EHND6 070       0.63         49         5150           11    
11     EHN

34     EHND7     EHND7 - 002         59        NaN         NaN
  Unnamed: 0      Unnamed: 1 ME-ICP61S  PGM-MS23  PGM-MS23 .1
0        NaN             NaN        Zn        Pt          Pd 
1   Hole No   Sample Number        ppm       ppm         ppm 
2     EHND7       EHND7 003         77        NaN         NaN
3     EHND7       EHND7 004         80        NaN         NaN
4     EHND7       EHND7 005         74        NaN         NaN
5     EHND8       EHND8 001         73    0.0025       0.006 
6     EHND8       EHND8 002         84    0.0458       0.052 
7     EHND8       EHND8 003         65    0.0236       0.029 
8     EHND8       EHND8 004         77    0.0118       0.016 
9     EHND8       EHND8 005         89     0.017       0.021 
  MAGNETITC  Unnamed: 1
1    HOLE :      EHND3 
  MAGNETITC  Unnamed: 1
1    HOLE :      EHND4 
  MAGNETITC  Unnamed: 1
1     HOLE:      EHND5 
  MAGNETITC  Unnamed: 1
1      HOLE      EHND6 
  MAGNETITC  Unnamed: 1
1      HOLE      EHND7 
  MAGNETITC  Un

30        NaN          NaN              NaN  
         Unnamed: 0                                     Peter Gregory 
0               NaN                               Principal Geologist 
1               NaN                               Geo Discovery Group 
2               NaN                                         PO Box 59 
3               NaN                                 SHERWOOD QLD 4075 
5             TO :                                          Ian Sandl 
6               NaN                                      Teck Cominco 
7               NaN                                       PO Box 1677 
8               NaN                                WEST PERTH WA 6872 
9      REFERENCE :                  E-mail from Peter Gregory 5/9/06. 
10      MATERIAL :              Ernest Henry North Drill Core Samples 
11  IDENTIFICATION                   EHND3 - 313.40 to EHND8 - 276.70 
12     REQUESTED :   Polished thin section preparation, description...
13    & SECTIONS :   Returned t

In [6]:
bt.train(n_queries=20)

           From            To                          Description 
0          6:00          7:00                       Travel to site 
1          7:00          7:45                    Pre start Toolbox 
2     7:45 8:00          8:00                       Flush hole 154 
3            NaN        17:00                    Core ahead to 57m 
5   17:00 17:30   17:30 18:00   Flush hole Packup Travel from site 
6         18:00            NaN                                  NaN
27           NaN           NaN                  Well site Visitors 
28         From            To                          Description 
29         7:15         15:15                             Jim Cole 
32          BHA            NaN            99mm HQ Surface bit 7.2m 
33           NaN           NaN           Operations for next 24hrs 
34           NaN           NaN                          Core ahead 

69109 table:  42

queries:  20
predict proba of this sample:  [[0.83384217 0.16615783]]
Prediction:  [0]

Enter one

C:\Anaconda\envs\gsq\lib\site-packages\sklearn\base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)


ActiveLearner(X_training=array([["['Date ', 'Depth Driller ', 'Depth Logger ', 'Log Top ', 'Log Bottom ', 'Bit Size ', 'Casing OD ', 'Casing ID ', 'Casing Weight ', 'Casing Shoe Driller ', 'Casing Shoe Logger ', 'Drill Measured From ', 'GL ', 'Log Measured From ', 'GL ', 'Rig ', 'Drillstrallis 1 ', 'Recorded by ', 'S.Wallis ', 'Recorded by ', 'E.Josey ', 'Logging Unit ', 'Witnessed ', 'S.Nicholson ']"],
       ['[\'TYPE OF...
                                                         preprocessor=None,
                                                         smooth_idf=True,
                                                         stop_words=None,
                                                         strip_accents=None,
                                                         sublinear_tf=False,
                                                         token_pattern='(?u)\\b\\w\\w+\\b',
                                                         tokenizer=None,
                           

AttributeError: 'list' object has no attribute 'shape'

In [4]:
res.loc[res['DocID'] == '37802']

DocID TableNum                                            Columns  Class  \
23  37802       10  ['From (m) ', 'To (m) ', 'Hole Diameter & Dril...    1.0   
51  37802       38  ['Depth From ', 'Depth To ', 'Average Gas unit...    1.0   

       proba  
23  0.961729  
51  0.668130

In [5]:
res.loc[res['DocID'] == '32730']

DocID TableNum                                            Columns  Class  \
11  32730        2  ['HOLE ', 'EASTING ', 'NORTHING ', 'RL ', 'DRI...    1.0   

       proba  
11  0.999997

In [3]:
res['Columns'][8]

"['SDA No ', 'Lab Job No ', 'Sample From ', 'Sample to ', 'Assay Type ', 'NWQ05DXJ011 ', 'TV05101133 ', 'ARA43425 ', 'ARA43573 ', 'ME-ICP41 & Au AA21 ', 'NWQ05DXJ012 ', 'TV05101134 ', 'EB22116 ', 'EB22145 ', 'ME-ICP61 & Au AA21 ']"

In [4]:

clf = bt.train(0)
# eli5.show_weights(clf)

training with all labelled samples
test set size:  0.2
[Pipeline] .......... (step 1 of 3) Processing list2str, total=   0.0s
[Pipeline] ............. (step 2 of 3) Processing tfidf, total=   0.4s
[Pipeline] ............... (step 3 of 3) Processing cnb, total=   0.0s
Test set results: 
0.9411764705882353
[[106   3]
 [  4   6]]
For manually annotated:
0.9865319865319865
[[533   4]
 [  4  53]]


In [5]:
df = bt.create_dataset(['2646', '44448', '32730', '37802', '44603'], save=False)
df

DocID TableNum                                            Columns
0     2646        1  [Unnamed: 0, Page , OBJECTIVES , DRILLING , GE...
1     2646        2  [Bore , Total Depth , Depth to Coal , Coal Thi...
2     2646        3  [Bore , Seam Thickness , Recovery , Moisture ,...
3    44448        1  [TITLE: , EXPLORATION PERMIT FOR MINERALS No 9...
4    44448        2                                                 []
..     ...      ...                                                ...
216  44603      136  [Unnamed: 0, Unnamed: 1, generally oblique or ...
217  44603      137  [Telephone: , Fax: (02) 4579 1290 , Unnamed: 3...
218  44603      138  [t.b refer to , Unnamed: 1, subsamples , from ...
219  44603      139  [Unnamed: 0, EXPLORATION , LIMITED , Unnamed: ...
220  44603      140  [Unnamed: 0, Unnamed: 1, Unnamed: 2, felsic , ...

[221 rows x 3 columns]

In [6]:
df = df.loc[df['Columns'].str.len() > 0]
res = bt.get_borehole_tables(df, masked=True)
res

C:\Users\andraszeka\OneDrive - ITP (Queensland Government)\gsq-boreholes\textracting\borehole_tables.py:151: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Columns'] = df['Columns'].astype(str)
C:\Users\andraszeka\OneDrive - ITP (Queensland Government)\gsq-boreholes\textracting\bookmarker\machine_learning_helper.py:90: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[y_column] = classes
C:\Users\andraszeka\OneDrive - ITP (Queensland Government)\gsq-boreholes\textracting\bookmarker\machine_learning_help

DocID TableNum                                            Columns  Class  \
1     2646        2  ['Bore ', 'Total Depth ', 'Depth to Coal ', 'C...    1.0   
134  44603       54  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'ME...    1.0   
135  44603       55  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'ME...    1.0   
137  44603       57  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'ME...    1.0   
144  44603       64  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'ME...    1.0   
145  44603       65  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'ME...    1.0   
147  44603       67  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'ME...    1.0   
154  44603       74  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'PG...    1.0   
155  44603       75  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'PG...    1.0   
156  44603       76  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'PG...    1.0   
157  44603       77  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'PG...    1.0   
158  44603       78  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61s ', 'PG...    1.0   
163  44603       83  ['Unnamed: 0', 'Unnamed: 1', 'ME-ICP61S ', 'PG...    1.0   
186  44603      106  ['TeckCominco: Bulk ', 'Density ', 'Measuremen...    1.0   
187  44603      107  ['TeckCominco: Bulk Density ', 'Unnamed: 1', '...    1.0   

     proba  
1      0.5  
134    0.5  
135    0.5  
137    0.5  
144    0.5  
145    0.5  
147    0.5  
154    0.5  
155    0.5  
156    0.5  
157    0.5  
158    0.5  
163    0.5  
186    0.5  
187    0.5

In [2]:
import borehole_tables

borehole_tables.train(n_queries=0)

training with all labelled samples
test set size:  0.2
[Pipeline] .......... (step 1 of 3) Processing list2str, total=   0.0s
[Pipeline] ............. (step 2 of 3) Processing tfidf, total=   0.3s
[Pipeline] ............... (step 3 of 3) Processing cnb, total=   0.0s
Test set results: 
0.9652173913043478
[[100   2]
 [  2  11]]
For manually annotated:
0.9910714285714286
[[491   2]
 [  3  64]]


In [1]:
from __future__ import print_function
import numpy as np
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets
from transformers import pipeline
from transformers import *

In [4]:
nlp = pipeline('fill-mask')
nlp(f'The relinquished portions of EPM 11177 are located south-east and south-west of {nlp.tokenizer.mask_token} (see Drawing 333.A4.02) and are within Roxmere Holding (PH 4893)and The Gorge Holding (PH 2330). The relinquished areas lie on the Cloncurry SF 54-02 1:250,000 sheet, and on two 1:100,000 map sheets: Marraba 6956 and Cloncurry 7056.')

Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/distilroberta-base-modelcard.json' to download model card file.
Creating an empty model card.


[{'sequence': '<s> The relinquished portions of EPM 11177 are located south-east and south-west of Perth (see Drawing 333.A4.02) and are within Roxmere Holding (PH 4893)and The Gorge Holding (PH 2330). The relinquished areas lie on the Cloncurry SF 54-02 1:250,000 sheet, and on two 1:100,000 map sheets: Marraba 6956 and Cloncurry 7056.</s>',
  'score': 0.08063917607069016,
  'token': 11426},
 {'sequence': '<s> The relinquished portions of EPM 11177 are located south-east and south-west of Newcastle (see Drawing 333.A4.02) and are within Roxmere Holding (PH 4893)and The Gorge Holding (PH 2330). The relinquished areas lie on the Cloncurry SF 54-02 1:250,000 sheet, and on two 1:100,000 map sheets: Marraba 6956 and Cloncurry 7056.</s>',
  'score': 0.03402038291096687,
  'token': 8983},
 {'sequence': '<s> The relinquished portions of EPM 11177 are located south-east and south-west of Aberdeen (see Drawing 333.A4.02) and are within Roxmere Holding (PH 4893)and The Gorge Holding (PH 2330). Th

In [5]:
ner = pipeline('ner')
ner('The relinquished portions of EPM 11177 are located south-east and south-west of Cloncurry River (see Drawing 333.A4.02) and are within Roxmere Holding (PH 4893)and The Gorge Holding (PH 2330). The relinquished areas lie on the Cloncurry SF 54-02 1:250,000 sheet, and on two 1:100,000 map sheets: Marraba 6956 and Cloncurry 7056.')

Model name 'dbmdz/bert-large-cased-finetuned-conll03-english' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased, bart-large, bart-large-mnli, bart-cnn, openai-gpt, transfo-xl-wt103, gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2, ctrl, xlnet-base-cased, xlnet-large-cased, xlm-mlm-en-2048, xlm-mlm-ende-1024, xlm-mlm-enfr-1024, xlm-mlm-enro-1024, 

[{'word': 'EP', 'score': 0.7242443561553955, 'entity': 'I-ORG'},
 {'word': 'C', 'score': 0.9810060858726501, 'entity': 'I-LOC'},
 {'word': '##lon', 'score': 0.9262786507606506, 'entity': 'I-LOC'},
 {'word': '##cu', 'score': 0.8185464143753052, 'entity': 'I-LOC'},
 {'word': '##rry', 'score': 0.861258864402771, 'entity': 'I-LOC'},
 {'word': 'River', 'score': 0.9517391324043274, 'entity': 'I-LOC'},
 {'word': 'R', 'score': 0.9982651472091675, 'entity': 'I-ORG'},
 {'word': '##ox', 'score': 0.9883707761764526, 'entity': 'I-ORG'},
 {'word': '##mere', 'score': 0.9966741800308228, 'entity': 'I-ORG'},
 {'word': 'Holding', 'score': 0.9903208613395691, 'entity': 'I-ORG'},
 {'word': 'The', 'score': 0.9730550646781921, 'entity': 'I-ORG'},
 {'word': 'Gorge', 'score': 0.9849491119384766, 'entity': 'I-ORG'},
 {'word': 'Holding', 'score': 0.982978105545044, 'entity': 'I-ORG'},
 {'word': 'C', 'score': 0.5953745245933533, 'entity': 'I-ORG'},
 {'word': '##lon', 'score': 0.5463330745697021, 'entity': 'I-ORG

In [13]:
import os

proxies = {
    "http": os.environ['http_proxy'],
    "https": os.environ['https_proxy']
}


In [14]:
new = pipeline('ner', proxies=proxies)#, model='bert-large-uncased', tokenizer=BertTokenizer)
new('Work completed on the relinquished area included stream sediment sampling, which was part of a regional program that collected samples for BLEG and multi-element analysis. A total of three stream sites were sampled on the relinquished area.')

Model name 'dbmdz/bert-large-cased-finetuned-conll03-english' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-japanese, bert-base-japanese-whole-word-masking, bert-base-japanese-char, bert-base-japanese-char-whole-word-masking, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased, bart-large, bart-large-mnli, bart-cnn, openai-gpt, transfo-xl-wt103, gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2, ctrl, xlnet-base-cased, xlnet-large-cased, xlm-mlm-en-2048, xlm-mlm-ende-1024, xlm-mlm-enfr-1024, xlm-mlm-enro-1024, 

TypeError: __init__() got an unexpected keyword argument 'proxies'